language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean && hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "palmerye"
  - git config user.email "palmerye@gmail.com"
  - git add .
  - git commit -m ":memo:\ Update docs by CI"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/palmerye/palmerye.github.io.git